Implemented a simple springboot database application
IAMNOTABARISTA/notabarista pull request #36
Opened 2020-09-30 21:53 UTC by SeifMostafaa

simple springboot application using mysql with simple crud operations

2020-10-01 07:28 UTC, adriannecula requested changes
implement review fidings

2020-10-01 13:49 UTC, SeifMostafaa reviewed
updated .gitignore file to exclude all unwanted files

2020-10-01 14:03 UTC, adriannecula approved these changes

2020-10-01 14:21 UTC, gunjanmimo approved these changes
LGTM

2020-10-01 15:23 UTC, alexandru-damian commented on helloworld/com/example/demo/Notabarista.java
> +public class Notabarista implements Serializable {
Why do we have two Notabarista classes?

2020-10-25 15:22 UTC, alexandru-damian requested changes
Binaries, shouldn't be in this repository. Are those .class files required to be added?

2022-05-15 13:22 UTC, closed without merging